version: '3.7'
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/hosts:/etc/nginx/conf.d
            - ./nginx/www:/var/www
            - ./nginx/logs:/var/log/nginx
            - ./nginx/certbot/conf:/etc/letsencrypt
            - ./nginx/certbot/www:/var/www/certbot
        links:
            - php
        networks:
            - test-project

    php:
        build: ./images/php
        container_name: php
        ports:
            - "9000:9000"
        volumes:
            - ./nginx/www:/var/www
        links:
            - mysql
        networks:
            - test-project

    certbot:
        container_name: certbot
        image: certbot/certbot
        volumes:
            - ./nginx/certbot/conf:/etc/letsencrypt
            - ./nginx/certbot/www:/var/www/certbot
        networks:
            - test-project

    mysql:
        image: mysql:latest
        container_name: mysql
        ports:
            - "3306:3306"
        volumes:
            - /var/lib/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: rootProject
            MYSQL_DATABASE: test-project
            MYSQL_USER: user
            MYSQL_PASSWORD: project
        networks:
            - test-project

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - 8090:80
        links:
            - mysql:db
        networks:
            - test-project

networks:
  test-project:
    driver: bridge
